REGION_MAP = {
    "Afghanistan": "Middle East",
    "Albania": "Europe",
    "Algeria": "Middle East",
    "American Samoa": "Pacific",
    "Andorra": "Europe",
    "Angola": "Africa",
    "Anguilla": "Latin America and the Caribbean",
    "Antigua and Barbuda": "Latin America and the Caribbean",
    "Argentina": "Latin America and the Caribbean",
    "Armenia": "Russian-speaking world",
    "Aruba": "Latin America and the Caribbean",
    "Australia": "Pacific",
    "Austria": "Europe",
    "Azerbaijan": "Russian-speaking world",
    "Bahamas": "Latin America and the Caribbean",
    "Bahrain": "Middle East",
    "Bangladesh": "South Asia",
    "Barbados": "Latin America and the Caribbean",
    "Belarus": "Russian-speaking world",
    "Belgium": "Europe",
    "Belize": "Latin America and the Caribbean",
    "Benin": "Africa",
    "Bermuda": "Latin America and the Caribbean",
    "Bhutan": "South Asia",
    "Bolivia": "Latin America and the Caribbean",
    "Bonaire": "Latin America and the Caribbean",
    "Bosnia and Herzegovina": "Europe",
    "Botswana": "Africa",
    "Brazil": "Latin America and the Caribbean",
    "British Indian Ocean Territory": "South Asia",
    "British Virgin Islands": "Latin America and the Caribbean",
    "Brunei": "East Asia",
    "Brunei Darussalam": "East Asia",
    "Bulgaria": "Europe",
    "Burkina Faso": "Africa",
    "Burundi": "Africa",
    "Cambodia": "East Asia",
    "Cameroon": "Africa",
    "Canada": "North America",
    "Cape Verde": "Africa",
    "Cayman Islands": "Latin America and the Caribbean",
    "Central African Republic": "Africa",
    "Chad": "Africa",
    "Chile": "Latin America and the Caribbean",
    "China": "East Asia",
    "Christmas Island": "Pacific",
    "Cocos Islands": "Pacific",
    "Colombia": "Latin America and the Caribbean",
    "Comoros": "Africa",
    "Congo": "Africa",
    "Congo - Brazzaville": "Africa",
    "Congo - Kinshasa (DRC)": "Africa",
    "Cook Islands": "Pacific",
    "Costa Rica": "Latin America and the Caribbean",
    "Cote D'Ivoire": "Africa",
    "Croatia": "Europe",
    "Cuba": "Latin America and the Caribbean",
    "Curacao": "Latin America and the Caribbean",
    "Cyprus": "Europe",
    "Czech Republic": "Europe",
    "Denmark": "Europe",
    "Djibouti": "Africa",
    "Dominica": "Latin America and the Caribbean",
    "Dominican Republic": "Latin America and the Caribbean",
    "East Timor": "East Asia",
    "Ecuador": "Latin America and the Caribbean",
    "Egypt": "Middle East",
    "El Salvador": "Latin America and the Caribbean",
    "Equatorial Guinea": "Africa",
    "Eritrea": "Africa",
    "Estonia": "Russian-speaking world",
    "Ethiopia": "Africa",
    "Falkland Islands": "Latin America and the Caribbean",
    "Faroe Islands": "Europe",
    "Federated States of Micronesia": "Pacific",
    "Fiji": "Pacific",
    "Finland": "Europe",
    "France": "Europe",
    "French Guiana": "Latin America and the Caribbean",
    "French Polynesia": "Pacific",
    "Gabon": "Africa",
    "Gambia": "Africa",
    "Georgia": "Russian-speaking world",
    "Germany": "Europe",
    "Ghana": "Africa",
    "Gibraltar": "Europe",
    "Greece": "Europe",
    "Greenland": "Europe",
    "Grenada": "Latin America and the Caribbean",
    "Guadeloupe": "Latin America and the Caribbean",
    "Guam": "Pacific",
    "Guatemala": "Latin America and the Caribbean",
    "Guernsey": "Europe",
    "Guinea": "Africa",
    "Guinea-Bissau": "Africa",
    "Guyana": "Latin America and the Caribbean",
    "Haiti": "Latin America and the Caribbean",
    "Honduras": "Latin America and the Caribbean",
    "Hong Kong": "East Asia",
    "Hungary": "Europe",
    "Iceland": "Europe",
    "India": "South Asia",
    "Indonesia": "East Asia",
    "Iran": "Middle East",
    "Iraq": "Middle East",
    "Ireland": "Europe",
    "Israel": "Middle East",
    "Italy": "Europe",
    "Jamaica": "Latin America and the Caribbean",
    "Japan": "East Asia",
    "Jordan": "Middle East",
    "Kazakhstan": "Russian-speaking world",
    "Kenya": "Africa",
    "Kiribati": "Pacific",
    "Kosovo": "Europe",
    "Kuwait": "Middle East",
    "Kyrgyzstan": "Russian-speaking world",
    "Laos": "East Asia",
    "Latvia": "Russian-speaking world",
    "Lebanon": "Middle East",
    "Lesotho": "Africa",
    "Liberia": "Africa",
    "Libya": "Middle East",
    "Liechtenstein": "Europe",
    "Lithuania": "Russian-speaking world",
    "Luxembourg": "Europe",
    "Macau": "East Asia",
    "Madagascar": "Africa",
    "Malawi": "Africa",
    "Malaysia": "East Asia",
    "Maldives": "South Asia",
    "Mali": "Africa",
    "Malta": "Europe",
    "Marshall Islands": "Pacific",
    "Martinique": "Latin America and the Caribbean",
    "Mauritania": "Africa",
    "Mauritius": "Pacific",
    "Mexico": "Latin America and the Caribbean",
    "Moldova": "Europe",
    "Monaco": "Europe",
    "Mongolia": "EAst Asia",
    "Montenegro": "Europe",
    "Montserrat": "Latin America and the Caribbean",
    "Morocco": "Middle East",
    "Mozambique": "Africa",
    "Myanmar / Burma": "EAst Asia",
    "Namibia": "Africa",
    "Nauru": "Pacific",
    "Nepal": "South Asia",
    "Netherlands": "Europe",
    "Netherlands Antilles": "Latin America and the Caribbean",
    "New Caledonia": "Pacific",
    "New Zealand": "Pacific",
    "Nicaragua": "Latin America and the Caribbean",
    "Niger": "Africa",
    "Nigeria": "Africa",
    "North Korea": "East Asia",
    "Northern Mariana Islands": "Pacific",
    "Norway": "Europe",
    "Oman": "Middle East",
    "Pakistan": "South Asia",
    "Palau": "Pacific",
    "Palestine": "Middle East",
    "Panama": "Latin America and the Caribbean",
    "Papua New Guinea": "Pacific",
    "Paraguay": "Latin America and the Caribbean",
    "Peru": "Latin America and the Caribbean",
    "Philippines": "East Asia",
    "Pitcairn": "Pacific",
    "Poland": "Europe",
    "Portugal": "Europe",
    "Puerto Rico": "Latin America and the Caribbean",
    "Qatar": "Middle East",
    "Republic of Macedonia": "Europe",
    "Reunion": "Pacific",
    "Romania": "Europe",
    "Russia": "Russian-speaking world",
    "Rwanda": "Africa",
    "Saint Helena": "Pacific",
    "Saint Kitts and Nevis": "Latin America and the Caribbean",
    "Saint Lucia": "Latin America and the Caribbean",
    "Saint Pierre and Miquelon": "Europe",
    "Saint Vincent and The Grenadines": "Latin America and the Caribbean",
    "Samoa": "Pacific",
    "San Marino": "Europe",
    "Sao Tome and Principe": "Africa",
    "Saudi Arabia": "Middle East",
    "Senegal": "Africa",
    "Serbia": "Europe",
    "Seychelles": "Africa",
    "Sierra Leone": "Africa",
    "Singapore": "East Asia",
    "Slovakia": "Europe",
    "Slovenia": "Europe",
    "Solomon Islands": "Pacific",
    "Somalia": "Africa",
    "Somaliland": "Africa",
    "South Africa": "Africa",
    "South Georgia and the South Sandwich Islands": "Europe",
    "South Korea": "East Asia",
    "South Sudan": "Africa",
    "Spain": "Europe",
    "Sri Lanka": "South Asia",
    "Sudan": "Africa",
    "Suriname": "Latin America and the Caribbean",
    "Swaziland": "Africa",
    "Sweden": "Europe",
    "Switzerland": "Europe",
    "Syrian Arab Republic": "Middle East",
    "Taiwan": "East Asia",
    "Tajikistan": "Russian-speaking world",
    "Tanzania": "Africa",
    "Thailand": "East Asia",
    "Togo": "Africa",
    "Tokelau": "Pacific",
    "Tonga": "Pacific",
    "Trinidad and Tobago": "Latin America and the Caribbean",
    "Tunisia": "Middle East",
    "Turkey": "Europe",
    "Turkmenistan": "Russian-speaking world",
    "Turks and Caicos Islands": "Latin America and the Caribbean",
    "Tuvalu": "Pacific",
    "U.S. Virgin Islands": "North America",
    "Uganda": "Africa",
    "Ukraine": "Russian-speaking world",
    "United Arab Emirates": "Middle East",
    "United Kingdom": "Europe",
    "United States": "North America",
    "Uruguay": "Latin America and the Caribbean",
    "Uzbekistan": "Russian-speaking world",
    "Vanuatu": "Pacific",
    "Vatican City State": "Europe",
    "Venezuela": "Latin America and the Caribbean",
    "Vietnam": "East Asia",
    "Wallis and Futuna": "Pacific",
    "Western Sahara": "Africa",
    "Yemen": "Middle East",
    "Zambia": "Africa",
    "Zimbabwe": "Africa",
}
